### ISSUE TITLE
Getting the following error when sending messages to the staff chat Discord channel

### ISSUE THREAD

**Issue by GrilledCow** [DiscordSRV/Staff-Chat#20]
The plugin was working fine when I first set it up, now when a staff member speaks in the staff chat channel in Discord the following error is shown in console.

When a staff member uses staff chat in-game it is sent to the channel without error. Using DiscordSRV 1.21.2 and staff chat 1.3.2.

`[06:01:07 WARN]: [DiscordSRV-Staff-Chat] Task #331388 for DiscordSRV-Staff-Chat v1.3.2 generated an exception
java.lang.NoClassDefFoundError: com/vdurmont/emoji/EmojiParser
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-394]
at com.rezzedup.discordsrv.staffchat.listeners.DiscordStaffChatListener.lambda$onDiscordChat$0(DiscordStaffChatListener.java:22) ~[?:?]
at com.rezzedup.discordsrv.staffchat.StaffChatPlugin.submitMessageFromDiscord(StaffChatPlugin.java:188) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-394]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-394]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1289) ~[patched_1.16.4.jar:git-Paper-394]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1204) ~[patched_1.16.4.jar:git-Paper-394]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-394]
at java.lang.Thread.run(Thread.java:834) [?:?]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-394]
`

Any help is appreciated, let me know if you require further info :)

**Comment by RezzedUp** [comment]
Thanks for reporting this - it's now fixed in v1.3.3.
