### ISSUE TITLE
Crash on 1.21.3

### ISSUE THREAD

**Issue by RocketManKian** [DiscordSRV/Staff-Chat#47]
[10:18:35 ERROR]: [SimpleProviderStorage] Circular plugin loading detected!
[10:18:35 ERROR]: [SimpleProviderStorage] Circular load order:
[10:18:35 ERROR]: [SimpleProviderStorage]   DiscordSRV-Staff-Chat -> DiscordSRV -> Essentials -> ServerEssentials -> DiscordSRV-Staff-Chat
[10:18:35 ERROR]: [SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.
[10:18:35 ERROR]: [SimpleProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
[10:18:35 ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Circular plugin loading from plugins DiscordSRV-Staff-Chat
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.handleCycle(SimpleProviderStorage.java:78) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:42) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:561) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by RezzedUp** [comment]
The real culprit here is ServerEssentials, which softdepends on DiscordSRV-Staff-Chat for some reason. I would ask the ServerEssentials dev to remove the soft dependency on DiscordSRV-Staff-Chat since it doesn't seem to interact with it at all. Meanwhile, that dev should probably fix up all their other dependencies because this circular dependency problem won't go away for other plugins in their softdepend list.
